name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: cd /home/nikcadez/personal-website && git pull origin main

      - name: Build and restart
        run: cd /home/nikcadez/personal-website && docker compose up -d --build

      - name: Clean up old images
        run: docker image prune -f
